export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as TrustBar } from "./TrustBar";
export { default as Solutions } from "./Solutions";
export { default as Features } from "./Features";
export { default as Testimonials } from "./Testimonials";
export { default as Stats } from "./Stats";
export { default as CTA } from "./CTA";
